// <auto-generated />
using System;
using AegisOrbit.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AegisOrbit.API.Migrations
{
    [DbContext(typeof(AegisOrbitContext))]
    [Migration("20260609034552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AegisOrbit.API.Domain.Entities.SpacialObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<double>("Mass")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)");

                    b.Property<double>("Velocity")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("SpacialObjects");

                    b.HasDiscriminator<string>("ObjectType").HasValue("SpacialObject");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AegisOrbit.API.Domain.Entities.ActiveSatellite", b =>
                {
                    b.HasBaseType("AegisOrbit.API.Domain.Entities.SpacialObject");

                    b.Property<bool>("IsSignalActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("OperatingFrequency")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasDiscriminator().HasValue("Satellite");
                });

            modelBuilder.Entity("AegisOrbit.API.Domain.Entities.DebrisSpace", b =>
                {
                    b.HasBaseType("AegisOrbit.API.Domain.Entities.SpacialObject");

                    b.Property<double>("EstimatedSizeMeters")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasDiscriminator().HasValue("Debris");
                });

            modelBuilder.Entity("AegisOrbit.API.Domain.Entities.SpacialObject", b =>
                {
                    b.OwnsOne("AegisOrbit.API.Domain.ValueObjects.OrbitalCoordinates", "CurrentPosition", b1 =>
                        {
                            b1.Property<Guid>("SpacialObjectId")
                                .HasColumnType("RAW(16)");

                            b1.Property<double>("Altitude")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("Altitude");

                            b1.Property<double>("Latitude")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("BINARY_DOUBLE")
                                .HasColumnName("Longitude");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("TIMESTAMP(7)")
                                .HasColumnName("PositionUpdatedAt");

                            b1.HasKey("SpacialObjectId");

                            b1.ToTable("SpacialObjects");

                            b1.WithOwner()
                                .HasForeignKey("SpacialObjectId");
                        });

                    b.Navigation("CurrentPosition")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
